version: '3.8'
services:
  todo-app:
    image: 'todo-app'
    build:
      context: .
    container_name: todo-app
    depends_on:
      - postgres_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/todo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres123
      - SPRING_FLYWAY_URL=jdbc:postgresql://postgres_db:5432/todo
      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=postgres123
      - SPRING_FLYWAY_LOCATIONS=classpath:db/migration
    ports:
      - "8080:8080"
  postgres_db:
    image: postgres:latest
    container_name: ToDoPostgresContainer
    restart: unless-stopped
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
    driver: local